#! /bin/sh
#! /bin/sh
if [ "$1" = "" ]; then
    echo "please tell me where to sync from (dir or host:dir)"
    exit 1
fi
if [ "$2" = "" ]; then
    echo "please tell me where to sync to (host:dir or dir)"
    exit 1
fi

# we'll see how crazy many backups we get with --suffix
rsync -avP \
      --delete \
      --backup-dir=/home/bmurdock/.local/sync-from-"$(uname -n)"-backup \
      --suffix=".$(date --rfc-3339=s)" \
      --exclude=.ICEauthority \
      --exclude=.Xauthority \
      --exclude=.altera.quartus \
      --exclude=.backups-emacs \
      --exclude=.bash_history \
      --exclude=.cache \
      --exclude=.ccache \
      --exclude=.config \
      --exclude=.dbus \
      --exclude=.direnv \
      --exclude=.docker \
      --exclude=.esd_auth \
      --exclude=.gconf \
      --exclude=.gem \
      --exclude=.gnome \
      --exclude=.hplip \
      --exclude=.java \
      --exclude=.lesshst \
      --exclude=.local \
      --exclude=.modelsim \
      --exclude=.mozilla \
      --exclude=.nfs* \
      --exclude=.npm \
      --exclude=.pki \
      --exclude=.python_history \
      --exclude=.ssh-agent-current \
      --exclude=.ssh/ssh_auth_sock_* \
      --exclude=.stversions \
      --exclude=.thunderbird \
      --exclude=.tramp_history \
      --exclude=.vnc \
      --exclude=.xinitrc \
      --exclude=.xorgxrdp* \
      --exclude=.xpra \
      --exclude=.xsession* \
      --exclude=Downloads \
      --exclude=cache \
      "$1" "$2"
